
name: 'Build Linux'

on:
  push:
    branches: [ master, development ]
    paths-ignore:
      - 'AdditionalFiles/**'
  pull_request:
    branches: [ master, development ]
    paths-ignore:
      - 'AdditionalFiles/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      
      # TODO: Cache shaderc
      
      - name: install-deps
        run: sudo apt-get update -m && sudo apt-get install -y cmake g++-multilib libopenal-dev python3 python3-dev xserver-xorg-dev libxcursor-dev libxi-dev libxrandr-dev libxinerama-dev automake libtool autoconf libbz2-dev uuid-dev
    
      - name: install-vulkan-sdk
        run: |
          wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add; \
          sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.2.131-bionic.list http://packages.lunarg.com/vulkan/1.2.131/lunarg-vulkan-1.2.131-bionic.list

      - name: create-build-directories
        run: |
          mkdir -p \
            FlexEngine/lib/x64/Debug/ \
            FlexEngine/dependencies/glfw/build/ \
            FlexEngine/dependencies/openAL/build/ \
            FlexEngine/dependencies/bullet/build/ \
            FlexEngine/dependencies/freetype/build/ \
            FlexEngine/dependencies/shaderc/build/

      - name: glfw-generate-build-files
        run: cmake -S FlexEngine/dependencies/glfw/ -B FlexEngine/dependencies/glfw/build/ -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF
      
      - name: glfw-build
        run: pushd FlexEngine/dependencies/glfw/build/ && make . && popd
      
      - name: copy-glfw-binaries
        uses: canastro/copy-action@master
        with:
          source: 'FlexEngine/dependencies/glfw/build/src/Debug/libglfw3.a'
          target: 'FlexEngine/lib/x64/Debug/'
      
      - name: install-genie
        run: |
          cd scripts; \
          sudo wget https://github.com/bkaradzic/bx/raw/master/tools/bin/linux/genie
          
      - name: run-genie
        run: |
          genie gmake; \
          cd ../
      
      - name: build
        run: |
          cd build/debug64/; \
          make .
